
SOCKET_SERVER_VERSION = "1.02"
SOCKET_API_VERSION = 2

SOCKET_MESSAGE_DISCONNECT = 0
SOCKET_MESSAGE_CONNECT = 1
SOCKET_MESSAGE_CONNECTED = 1
SOCKET_MESSAGE_READY = 2

SOCKET_MESSAGE_REGISTER = 5
SOCKET_MESSAGE_GET_CONFIG = 6
SOCKET_MESSAGE_CONFIG = 7

SOCKET_MESSAGE_GET_INDEX = 100
SOCKET_MESSAGE_INDEX = 101
SOCKET_MESSAGE_UPDATE = 102

SOCKET_MESSAGE_GET_STATUS = 105
SOCKET_MESSAGE_STATUS = 106

SOCKET_MESSAGE_GET_HASHLIST = 110
SOCKET_MESSAGE_HASHLIST = 111

SOCKET_MESSAGE_GET_BLOCK = 113
SOCKET_MESSAGE_BLOCK = 114

SOCKET_MESSAGE_GET_TRANSACTION = 116
SOCKET_MESSAGE_TRANSACTION = 117

SOCKET_MESSAGE_GET_QUERY = 119

SOCKET_MESSAGE_GET_TRANSACTIONS_SINCE = 123
SOCKET_MESSAGE_TRANSACTIONS_SINCE = 124

SOCKET_MESSAGE_WRITE_TRANSACTION = 150

SOCKET_MESSAGE_GET_SYNC_LOCK = 200
SOCKET_MESSAGE_SYNC_LOCK = 201

SOCKET_MESSAGE_SYNC_RELEASE = 202

