
# permission set

DATANODE_VERSION = 1

ACCESS_WRITEONLY = "w"
ACCESS_READONLY = "r"
ACCESS_READWRITE = "rw"
ACCESS_MASTER = "m"
ACCESS_PUBLIC = "p"
ACCESS_NONE = "o"

TIME_INTERVAL_REQUEST_IDXUPDATED = 5

MAX_LINE_LENGTH = 200
