
NOTIFY_CHAIN_LOADED = "NOTIFY_CHAIN_LOADED"
NOTIFY_CHAIN_INITIALIZED = "NOTIFY_CHAIN_INITIALIZED"
NOTIFY_CHAIN_RESET = "NOTIFY_CHAIN_RESET"
NOTIFY_CHAIN_TRANSACTIONS = "NOTIFY_CHAIN_TRANSACTIONS"

NOTIFY_CONFIG_CHANGED = "NOTIFY_CONFIG_CHANGED"
